// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEpbUdGtUMKNm3yANNCpl-Abbi8-_qk10',
    appId: '1:494957483440:web:80f6af5739e5aa9170b275',
    messagingSenderId: '494957483440',
    projectId: 'chat-app-817f3',
    authDomain: 'chat-app-817f3.firebaseapp.com',
    storageBucket: 'chat-app-817f3.appspot.com',
    measurementId: 'G-R46JFDZS9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZrFxL-BA5GwQRrbF-0cavwf8-9JPRXM',
    appId: '1:494957483440:android:392e39d06771465470b275',
    messagingSenderId: '494957483440',
    projectId: 'chat-app-817f3',
    storageBucket: 'chat-app-817f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC054cO9bAx-oHwn0uNru5cOCpe9oykflU',
    appId: '1:494957483440:ios:01cdd67027e4cb9970b275',
    messagingSenderId: '494957483440',
    projectId: 'chat-app-817f3',
    storageBucket: 'chat-app-817f3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC054cO9bAx-oHwn0uNru5cOCpe9oykflU',
    appId: '1:494957483440:ios:01cdd67027e4cb9970b275',
    messagingSenderId: '494957483440',
    projectId: 'chat-app-817f3',
    storageBucket: 'chat-app-817f3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEpbUdGtUMKNm3yANNCpl-Abbi8-_qk10',
    appId: '1:494957483440:web:5c7ae3d0d1260abd70b275',
    messagingSenderId: '494957483440',
    projectId: 'chat-app-817f3',
    authDomain: 'chat-app-817f3.firebaseapp.com',
    storageBucket: 'chat-app-817f3.appspot.com',
    measurementId: 'G-LSRTNRCNWF',
  );
}
